api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
     ##### SELLERS URLS #####
    path('seller/list/', views.ListSeller.as_view(), name="list_seller"),
    path('seller/detail/<int:pk>/', views.DetailSeller.as_view(), name="detail_seller"),
    path('seller/create/', views.CreateSeller.as_view(), name="create_seller"),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
   
]

whisse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
] 

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-1">

            </div>
            <div class="col-10">
                <div class="row">                  
                    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
                        <div class="container-fluid">
                          <a class="navbar-brand" href="{% url 'home:index' %}">ACI</a>
                          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                          </button>
                          <div class="collapse navbar-collapse" id="navbarColor01">
                            <ul class="navbar-nav me-auto">
                              <li class="nav-item">
                                <a class="nav-link active" href="{% url 'home:index' %}">Home
                                  <span class="visually-hidden">(current)</span>
                                </a>
                              </li>
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sellers</a>
                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{% url 'core:create_seller' %}">New Seller</a>
                                  <a class="dropdown-item" href="{% url 'core:list_seller' %}">List Seller</a>
                                  <a class="dropdown-item" href="#">List Seller-Clients</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#">List Seller-Sales</a>
                                </div>
                              </li>
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Clients</a>
                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="#">New Client</a>
                                  <a class="dropdown-item" href="#">List Client</a>
                                  <a class="dropdown-item" href="#"></a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#"></a>
                                </div>
                              </li>
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Products</a>
                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="#">New Product</a>
                                  <a class="dropdown-item" href="#">List Product</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#">New Product Categories</a>
                                  <a class="dropdown-item" href="#">List Product Categories</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#">New Product SubCategories</a>
                                  <a class="dropdown-item" href="#">List Product SubCategories</a>
                                </div>
                              </li>
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Services</a>
                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="#">New Services</a>
                                  <a class="dropdown-item" href="#">List Services</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#">New Services Category</a>
                                  <a class="dropdown-item" href="#">List Services Categories</a>                          
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#">New Services SubCategory</a>
                                  <a class="dropdown-item" href="#">List Services SubCategories</a>                                 
                                </div>
                              </li>
                            </ul>
                            <form class="d-flex">
                              <input class="form-control me-sm-2" type="search" placeholder="Search">
                              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                            </form>
                          </div>
                        </div>
                      </nav>
                </div>
                <br>
                <br>
                <div class="row">
                    {% block content %}
                       
                    {% endblock %}
                    <br>
                </div>
                <div class="row">
                  <footer class="bg-primary text-white text-center text-lg-start">
                    <!-- Grid container -->
                    <div class="container p-4">
                      <!--Grid row-->
                      <div class="row">
                        <!--Grid column-->
                        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                          <h5 class="text-uppercase">Footer Content</h5>
                  
                          <p>
                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                            molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                            voluptatem veniam, est atque cumque eum delectus sint!
                          </p>
                        </div>
                        <!--Grid column-->
                  
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                          <h5 class="text-uppercase">Links</h5>
                  
                          <ul class="list-unstyled mb-0">
                            <li>
                              <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                              <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                              <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                              <a href="#!" class="text-white">Link 4</a>
                            </li>
                          </ul>
                        </div>
                        <!--Grid column-->
                  
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                          <h5 class="text-uppercase mb-0">Links</h5>
                  
                          <ul class="list-unstyled">
                            <li>
                              <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                              <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                              <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                              <a href="#!" class="text-white">Link 4</a>
                            </li>
                          </ul>
                        </div>
                        <!--Grid column-->
                      </div>
                      <!--Grid row-->
                    </div>
                    <!-- Grid container -->
                  
                    <!-- Copyright -->
                    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                      © 2020 Copyright:
                      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
                    </div>
                    <!-- Copyright -->
                  </footer>
                </div>
            </div>
            <div class="col-1">

            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>