api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
     ##### SELLERS URLS #####
    path('seller/list/', views.ListSeller.as_view(), name="list_seller"),
    path('seller/detail/<int:pk>/', views.DetailSeller.as_view(), name="detail_seller"),
    path('seller/create/', views.CreateSeller.as_view(), name="create_seller"),
]

whisse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
] 

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


STATE_SALE = (
    ("Doing", "DG"),
    ("Done", "DN"),
    ("Pending", "PN"),
)

MONEY_TYPE = (
    ("Dolar USA", "DL"),
    ("Peso Mexicano", "MX"),
)

#Vendedor
class Seller(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=32, default="General Seller")
    certification = models.CharField(max_length=128, default="Generic Certification")
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    image = models.ImageField(upload_to='images/sellers/', default='general_selller.jpg', blank=True, null=True)
    bio = models.CharField(max_length=256, default="I Love ACI")
    status = models.BooleanField(default=True)
    slug = models.SlugField()

    def __str__(self):
        return self.name 


#Cliente
class Client(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    name = models.CharField(max_length=128, default="General Public")
    web_page = models.URLField(default="https://www.genericwebpage.com", blank=True, null=True)
    email = models.EmailField(default="genericemal@generic.com", blank=True, null=True)
    static_phone = models.CharField(max_length=13, default="1234567890", blank=True, null=True)
    celphone = models.CharField(max_length=10, default="1234567890")
    image = models.ImageField(upload_to='images/clients/', default='general_client.jpg', blank=True, null=True) 
    address = models.CharField(max_length=128, default="Tijuana BC", blank=True, null=True)
    visit_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    status = models.BooleanField(default=False)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    follow_up = models.BooleanField(default=False)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.name


# Product Category
class ProductCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_category_name = models.CharField(max_length=32, default="Generic Product Category", unique=True, blank=False, null=False)
    description = models.CharField(max_length=256, default="Generic Product Category Description")
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.product_category_name


# Product Subcategory
class ProductSubCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    product_subcategory_name = models.CharField(max_length=32, default="Generic Product SubCategory", unique=True, blank=False, null=False)
    description = models.CharField(max_length=256, default="Generic Product SubCategory Description")
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.product_subcategory_name


#Provider
class Provider(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    provider_name = models.CharField(max_length=32, default="Generic Provider")
    web_page = models.URLField(default="https://www.genericwebpage.com", blank=True, null=True)
    email = models.EmailField(default="genericemal@generic.com", blank=True, null=True)
    static_phone = models.CharField(max_length=13, default="1234567890", blank=True, null=True)
    image = models.ImageField(upload_to='images/clients/', default='general_client.jpg', blank=True, null=True) 
    address = models.CharField(max_length=128, default="Tijuana BC", blank=True, null=True)
    status = models.BooleanField(default=False)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.provider_name
    

#Producto

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=32, default="Generic Product")
    description = models.CharField(max_length=254)
    stock = models.IntegerField(default=0)
    price = models.FloatField(default=0.0)
    money_type = models.CharField(max_length=16, choices=MONEY_TYPE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.product_name



# Service Category
class ServiceCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service_category_name = models.CharField(max_length=32, default="Generic Service Category", unique=True, blank=False, null=False)
    description = models.CharField(max_length=256, default="Generic Product Service Category Description")
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.service_category_name


#Service Subcategory
class ServiceSubCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service_category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
    service_subcategory_name = models.CharField(max_length=32, default="Generic Service SubCategory", unique=True, blank=False, null=False)
    description = models.CharField(max_length=256, default="Generic Product Service SubCategory Description")
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.service_subcategory_name


#Servicio
class Service(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=32, default="Generic Service")
    description = models.CharField(max_length=254)
    stock = models.IntegerField(default=0)
    price = models.FloatField(default=0.0)
    money_type = models.CharField(max_length=16, choices=MONEY_TYPE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.service_name

#Venta

class Venta(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sell_code = models.CharField(max_length=64, default="Generic Sale by Generic Seller")
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True, related_name="products")
    services = models.ManyToManyField(Service, blank=True, related_name="services")
    total_sale = models.FloatField(default=0.0)
    money_type = models.CharField(max_length=16, choices=MONEY_TYPE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    state = models.CharField(max_length=16, choices=STATE_SALE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)


    def __str__(self):
        return self.sale_code

core/forms.py
from django import forms

from .models import Seller

class CreateSellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = [
            "user",
            "name",
            "certification",
            "image",
            "bio",
            "status",
            "slug"
        ]
        widgets = {
            "user": forms.Select(attrs={"type":"select", "class":"form-select"}),
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe Nombre del Seller"}),
            "certification": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe las Certificaciones del Seller"}),
            "image": forms.FileInput(attrs={"type":"file", "class":"form-control"}),
            "bio": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-check-input"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control"})
        }

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from core.models import Seller
from .forms import CreateSellerForm
# Create your views here.
##### S E L L E R C R U D  #####

# Create
class CreateSeller(generic.CreateView):
    template_name = "core/create_seller.html"
    model = Seller
    form_class = CreateSellerForm
    success_url = reverse_lazy("core:list_seller")
    

# Retrieve
class ListSeller(generic.View):
    template_name = "core/list_seller.html"
    context = {}

    def get(self, request):
        self.context = {
            "sellers": Seller.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    
class DetailSeller(generic.View):
    template_name = "core/detail_seller.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "seller": Seller.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

# Update

# Delete

templates/core/create_seller.html
{% extends "base/base.html" %}

{% block title %}
  CREATE NEW SELLER VIEW
{% endblock title %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <br>
    <button type="submit" class="btn btn-outline-success form-control">Create Seller</button>
    <br>
    <a href="{% url 'core:list_seller' %}" class="btn btn-outline-warning form-control">Cancel</a>
  </form>

{% endblock content %}

templates/core/detail_seller.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL SELLER VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          {{ seller.name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the {{ seller.name }}.</strong> {{ seller.bio }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Certification
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <ul class="list-group">
        
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  {{ seller.certification }}
                  <span class="badge bg-primary rounded-pill">14</span>
                </li>
                
              </ul>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Seller
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp seller {{ seller.timestamp }}</strong> And It is his status {{ seller.status }}
        </div>
      </div>
    </div>
  </div>
  <div class="justify-content-between">
    <a href="{% url 'core:list_seller' %}" class="btn btn-link">back to list</a>
  </div>
  
{% endblock content %}

templates/core/list_seller.html
{% extends "base/base.html" %}


{% block title %}
  LIST SELLER VIEW
{% endblock title %}

{% block content %}
  <table class="table table-striped table-hover table-responsive-lg">
    <thead>
        <th>ID</th>
        <th>SELLER NAME</th>
        <th>TIMESTAMP</th>
        <th>STATUS</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
    </thead>
    <tbody>
        {% for seller in sellers %}
          <tr>
            <td>{{ seller.id }}</td>
            <td>{{ seller.name }}</td>
            <td>{{ seller.timestamp }}</td>
            <td>{{ seller.status }}</td>
            <td><a href="{% url 'core:detail_seller' seller.id %}" class="btn btn-outline-info">Detail</a></td>
            <td><a href="" class="btn btn-outline-warning">Update</a></td>
            <td><a href="" class="btn btn-outline-danger">Delete</a></td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock content %}